plugin:
    name: 'shayankhaksar.zarinpal::lang.plugin.name'
    description: 'shayankhaksar.zarinpal::lang.plugin.description'
    author: Haminvara
    icon: oc-icon-money
    homepage: ''
permissions:
    shayankhaksar.zarinpal.manage_transaction:
        tab: 'Transaction Management'
        label: 'Transaction Management'
navigation:
    main-menu-item:
        label: Transactions
        url: shayankhaksar/zarinpal/transactions
        icon: icon-money
        permissions:
            - shayankhaksar.zarinpal.manage_transaction
        sideMenu:
            side-menu-item:
                label: 'shayankhaksar.zarinpal::lang.plugin.name'
                url: shayankhaksar/zarinpal/transactions
                icon: icon-money
