title: Transactions
modelClass: ShayanKhaksar\Zarinpal\Models\Transaction
list: $/ShayanKhaksar/zarinpal/models/transaction/columns.yaml
recordUrl: 'ShayanKhaksar/zarinpal/transactions/update/:transaction_id'
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
