title: Transactions
modelClass: at\Zarinpal\Models\Transaction
list: $/at/zarinpal/models/transaction/columns.yaml
recordUrl: 'at/zarinpal/transactions/update/:transaction_id'
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
