name: Transactions
form: $/shayankhaksar/zarinpal/models/transaction/fields.yaml
modelClass: shayankhaksar\Zarinpal\Models\Transaction
defaultRedirect: shayankhaksar/zarinpal/transactions
create:
    redirect: 'shayankhaksar/zarinpal/transactions/update/:id'
    redirectClose: shayankhaksar/zarinpal/transactions
update:
    redirect: shayankhaksar/zarinpal/transactions
    redirectClose: shayankhaksar/zarinpal/transactions
